export const workouts={
 rest:{name:'Rest day',time:'No session',desc:'Leave some space in your day. Rest belongs in your plan.',steps:['No workout to complete. Choose something restful if you like.'],easy:'Keep this day free of exercise plans.'},
 walk:{name:'Easy walk or roll',time:'5–10 min · Beginner',desc:'A comfortable outing, indoors or outdoors.',steps:['Choose a familiar, accessible route.','Move at a comfortable pace.','Turn back or stop whenever you want.'],easy:'A minute or two of comfortable movement, or choose rest.'},
 strength:{name:'Simple strength',time:'5–10 min · Beginner',desc:'An optional introduction. Skip any movement that does not suit you.',steps:['With a stable chair against a wall, try a few comfortable sit-to-stands.','Try a few gentle wall push-ups, with feet close to the wall.','Pause between movements. One comfortable round is enough.'],easy:'Choose one familiar movement, a walk, or rest.'},
 dance:{name:'One-song dance',time:'3–5 min · Beginner',desc:'Put on a song you like and move your own way.',steps:['Give yourself a clear, comfortable space.','Try gentle steps or seated movements.','Keep the pace easy and stop when you want.'],easy:'Enjoy part of a song with small seated movements, or rest.'},
 stretch:{name:'Gentle mobility',time:'3–5 min · Beginner',desc:'A few easy movements without pushing your range.',steps:['Try slow shoulder rolls in a comfortable position.','Gently open and close your hands.','Keep a comfortable range; no bouncing or forcing.'],easy:'Choose one comfortable movement or simply take a break.'}
};
export const meals=[
 {id:'oats',name:'Banana overnight oats',type:'Breakfast',time:'5 min + chilling',cost:'Pantry-friendly',ingredients:'Oats, milk or fortified soy drink, banana, optional peanut butter.',steps:'Mix oats with enough milk to moisten, cover, and refrigerate overnight. Add sliced banana before eating.',swap:'Use seasonal fruit. Skip peanut butter or use a seed butter if suitable.'},
 {id:'beans',name:'Beans on toast, your way',type:'Anytime',time:'10 min',cost:'Cupboard staples',ingredients:'Canned beans, bread, canned tomatoes, optional grated cheese.',steps:'Heat beans and tomatoes in a pan until hot throughout. Spoon onto toast and add cheese if you like.',swap:'Use lentils instead of beans, or serve over freshly cooked rice.'},
 {id:'pasta',name:'Peas & tomato pasta',type:'Lunch or dinner',time:'15 min',cost:'Freezer-friendly',ingredients:'Pasta, frozen peas, canned tomatoes, a little oil, optional cheese.',steps:'Cook pasta following its packet. Heat tomatoes and peas until cooked, then stir through drained pasta.',swap:'Try frozen mixed vegetables or add canned beans.'},
 {id:'potato',name:'Loaded jacket potato',type:'Lunch or dinner',time:'15 min in microwave',cost:'Simple staples',ingredients:'Potato, canned beans, plain yogurt or cheese, frozen vegetables.',steps:'Pierce the potato and microwave following your appliance guidance until soft. Heat beans and vegetables thoroughly; add your toppings.',swap:'Try a sweet potato or use cooked lentils.'},
 {id:'wrap',name:'Hummus crunch wrap',type:'Lunch',time:'5 min',cost:'No cooking needed',ingredients:'Wrap, hummus, grated carrot, cucumber, optional cheese.',steps:'Spread hummus over the wrap, add vegetables and any extras, then fold. Serve with whatever else helps make it a satisfying meal.',swap:'Use mashed beans; swap the wrap for bread or a rice bowl.'},
 {id:'eggs',name:'Egg & vegetable rice',type:'Lunch or dinner',time:'15 min',cost:'Flexible ingredients',ingredients:'Freshly cooked rice, eggs or tofu, frozen vegetables, a little oil.',steps:'Cook vegetables in a pan, add egg and stir until fully cooked (or heat tofu thoroughly). Stir in hot cooked rice.',swap:'Use a microwave rice pouch following its instructions. Choose tofu instead of eggs if preferred.'}
];
