export const KEY='kindly.v1';
export const goalChoices={move:['Move in a way I enjoy','Take a gentle movement break','Make room for rest'],meal:['Make a simple meal','Plan one affordable meal','Enjoy a meal without multitasking'],care:['Check in with my energy','Make time to unwind','Step outside for a moment']};
export function dateKey(date=new Date()){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,'0')}-${String(date.getDate()).padStart(2,'0')}`;}
export function weekDays(date=new Date(),offset=0){const d=new Date(date.getFullYear(),date.getMonth(),date.getDate());d.setDate(d.getDate()-((d.getDay()+6)%7)+offset*7);return Array.from({length:7},(_,i)=>{const x=new Date(d);x.setDate(d.getDate()+i);return dateKey(x);});}
export function freshState(){return {version:1,theme:'blue',days:{},plans:{},logs:[],favorites:[],foodJournal:[],showFlame:true,sessions:[]};}
export function dayFor(state,key){return state.days[key]??={goals:Object.fromEntries(Object.entries(goalChoices).map(([k,v])=>[k,{text:v[0],done:false}])),energy:null};}
export function restart(state,key){const day=dayFor(state,key);for(const [kind,text] of Object.entries({move:goalChoices.move[2],meal:goalChoices.meal[1],care:goalChoices.care[0]})){if(!day.goals[kind].done)day.goals[kind]={text,done:false};}return day;}
export function loadState(storage){try{const raw=storage.getItem(KEY);if(!raw)return {state:freshState()};const s=JSON.parse(raw);if(s.version!==1||!s.days||!s.plans||!Array.isArray(s.logs)||!Array.isArray(s.favorites))throw Error();return {state:{...freshState(),...s}};}catch{return {state:freshState(),error:'Saved data could not be read. Changes will not be saved until you export or delete the existing data in Settings.'};}}
export function saveState(storage,state){try{storage.setItem(KEY,JSON.stringify(state));return true;}catch{return false;}}
export function freshStore(){return {version:2,activeId:'default',profiles:[{id:'default',name:'My space',data:freshState()}]};}
export function validData(s){return s&&['blue','berry','night'].includes(s.theme)&&s.days&&typeof s.days==='object'&&!Array.isArray(s.days)&&Object.values(s.days).every(d=>d&&d.goals&&Object.keys(goalChoices).every(k=>d.goals[k]&&goalChoices[k].includes(d.goals[k].text)&&typeof d.goals[k].done==='boolean')&&[null,'Low','Steady','High'].includes(d.energy))&&s.plans&&typeof s.plans==='object'&&!Array.isArray(s.plans)&&Object.values(s.plans).every(p=>['rest','walk','strength','dance','stretch','bodylegs','dumbbells'].includes(p))&&Array.isArray(s.logs)&&s.logs.every(l=>l&&typeof l.id==='string'&&typeof l.date==='string'&&['strength','energy','habit'].includes(l.kind)&&typeof l.text==='string')&&Array.isArray(s.favorites)&&s.favorites.every(v=>typeof v==='string')&&(s.showFlame===undefined||typeof s.showFlame==='boolean')&&(s.sessions===undefined||Array.isArray(s.sessions)&&s.sessions.every(r=>r&&typeof r.id==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(r.date)&&['walk','strength','dance','stretch','bodylegs','dumbbells'].includes(r.workout)&&Number.isInteger(r.completed)&&Number.isInteger(r.total)&&r.completed>0&&r.completed<=r.total))&&(s.foodJournal===undefined||Array.isArray(s.foodJournal)&&s.foodJournal.every(e=>e&&typeof e.id==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(e.date)&&['Breakfast','Lunch','Dinner','Snack','Something else'].includes(e.kind)&&typeof e.text==='string'&&e.text.length<=500&&['','Comforting','Enjoyable','Energizing','Mixed','Prefer not to say'].includes(e.feeling)));}
export function loadStore(storage){try{const raw=storage.getItem(KEY);if(!raw)return {store:freshStore()};let s=JSON.parse(raw);if(s.version===1&&validData(s))s={version:2,activeId:'default',profiles:[{id:'default',name:'My space',data:s}]};if(s.version!==2||!Array.isArray(s.profiles)||!s.profiles.length||!s.profiles.every(p=>p&&typeof p.id==='string'&&typeof p.name==='string'&&validData(p.data))||!s.profiles.some(p=>p.id===s.activeId)||new Set(s.profiles.map(p=>p.id)).size!==s.profiles.length)throw Error();for(const p of s.profiles){p.data.foodJournal??=[];p.data.showFlame??=true;p.data.sessions??=[];}return {store:s};}catch{return {store:freshStore(),error:'Saved data could not be read. Changes will not be saved until you export or delete the existing data in Settings.'};}}
export function activeDays(state){return [...new Set([...Object.keys(state.days).filter(key=>state.days[key].energy||Object.values(state.days[key].goals).some(g=>g.done)),...state.logs.map(l=>l.date),...(state.foodJournal||[]).map(e=>e.date),...(state.sessions||[]).map(e=>e.date)])].sort();}
export function deleteStore(storage){storage.removeItem(KEY);return freshStore();}
export function reminderICS(localDateTime){const start=new Date(localDateTime);if(!Number.isFinite(start.getTime()))throw Error('Choose a valid date and time.');if(start<=new Date())throw Error('Choose a time in the future.');const stamp=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}/,'');return ['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Kindly//Gentle Reminder//EN','BEGIN:VEVENT',`UID:kindly-${start.getTime()}@local`,`DTSTAMP:${stamp(new Date())}`,`DTSTART:${stamp(start)}`,`DTEND:${stamp(new Date(start.getTime()+10*60000))}`,'SUMMARY:A little time for you','DESCRIPTION:Open Kindly when it suits you. One small step is enough.','BEGIN:VALARM','TRIGGER:PT0M','ACTION:DISPLAY','DESCRIPTION:A little time for you','END:VALARM','END:VEVENT','END:VCALENDAR',''].join('\r\n');}
