import {routines,movements,modes} from './training.js';
export function guideHTML(run){
 const routine=routines[run.workout];
 const close='<button class="guide-close" data-guide-action="close" aria-label="Close workout guide">×</button>';
 if(run.index===-1)return `${close}<span class="eyebrow">${modes[routine.mode].name} · BEGINNER GUIDE</span><h2 id="guide-title">${routine.name}</h2><p class="muted">${routine.description}</p><div class="guide-meta"><span>${routine.time} · flexible</span><span>${routine.gear}</span></div><ol class="guide-outline">${routine.moves.map(id=>`<li>${movements[id].name}</li>`).join('')}</ol><div class="note"><strong>Before you begin</strong><p>Move comfortably and keep breathing. Take breaks between movements; stop if you feel pain, dizzy, or unwell. These general guides aren’t a personal training plan.</p>${routine.mode==='weights'?'<p>Start without weights to learn the motion. If you’re new to lifting, get qualified instruction, especially if you’re under 18. No heavy or maximum lifts.</p>':''}</div><button class="primary wide" data-guide-action="next">Start the guide →</button><p class="form-note">A guide, not a race. Skip or leave whenever you want.</p>`;
 if(run.index>=routine.moves.length)return `${close}<div class="guide-finish"><span class="medal" aria-hidden="true">✦</span><h2 id="guide-title">A little counts.</h2><p>You tried ${run.done.length} of ${routine.moves.length} movements.</p><p class="muted">${run.done.length?'Save this session to your progress. It also counts toward today’s movement step.':'No pressure to complete a movement. You can close this guide or choose rest.'}</p>${run.done.length?'<button class="primary wide" data-guide-action="save">Save my session ✓</button>':'<button class="primary wide" data-guide-action="close">Close the guide</button>'}</div>`;
 const move=movements[routine.moves[run.index]];
 return `${close}<span class="eyebrow">MOVEMENT ${run.index+1} OF ${routine.moves.length}</span><progress value="${run.index}" max="${routine.moves.length}" aria-label="Guide position"></progress><h2 id="guide-title">${move.name}</h2><p class="muted">${move.pace}. Rest as needed.</p><ol class="how-to">${move.how.map(step=>`<li>${step}</li>`).join('')}</ol><div class="form-cue"><strong>Remember</strong><p>${move.tip}</p></div><details class="easy-option"><summary>Make it easier</summary><p>${move.easier}</p></details>${move.demo?`<a class="demo-link" href="${move.demo}" target="_blank" rel="noopener noreferrer">▶ Open ${move.source} ↗</a><p class="form-note">Opens another site. Internet required; no personal entries are sent.</p>`:''}<div class="guide-actions"><button class="primary wide" data-guide-action="done">I tried this · next →</button><div class="actions"><button class="quiet" data-guide-action="skip">Skip this move</button><button class="quiet" data-guide-action="back">Back</button></div></div>`;
}
